### ISSUE TITLE
Getting network error on firefox

### ISSUE THREAD

**Issue by mibcactus** [explodingcamera/lastfm-iceberg#1]
Using Firefox v105.0 64 Bit version on a windows 10 laptop, and I consistently get "Error: Network error when attempting to fetch resource". However, the generator worked fine on chrome.

**Comment by explodingcamera** [comment]
When I checked it out in the latest Firefox version, the page looked a bit wonky, which I just fixed, but I don't get the same error; you likely have some extension installed that is blocking the requests to last.fm's API.
