### ISSUE TITLE
Specific artist not appearing

### ISSUE THREAD

**Issue by JoeHiYo** [explodingcamera/lastfm-iceberg#2]
I have "Emerson, Lake & Palmer" in my top 100 (they are #35 in my top artists as of writing this) but they don't show up on my iceberg in any configuration. I thought it might be the punctuation, the ampersand in particular, but King Gizzard & The Lizard Wizard shows up just fine. Could it be the comma?

**Comment by explodingcamera** [comment]
Fixed in c4d1e4033106043fc65d4975bddb71afa58374c9
